# List of objects:
# e:							(STEP 0) new environment storing all variables/datasets/other objects generated by the program
# e$wd_recover		(STEP 0) default working directory used to recover the default path when TMV is over.	
# e$raw:   				(STEP 1) raw data for text mining
# e$rawc:					(STEP 2) corpus format of e$raw
# e$corpus0:			(STEP 2) corpus after series of corpus transformation except for stemming
# e$corpus0stem: 	(STEP 2) stemmed e$corpus0
# e$tdm0:					(STEP 3) term-document matrix of e$corpus0stem / then complete the stemmed terms by method "prevalent"
# e$tdmm0:				(STEP 3) matrix format of e$tdm0
# e$freq0:				(STEP 3) terms frequency (all terms without removing sparsity) by descending order in named vector format
# e$wf0:					(STEP 3) words frequency in data frame format based on e$tdmm0
# e$corpus1:			(STEP 4.1) corpus removing additional stopwords specified by users (based on e$corpus0)
# e$corpus1stem:	(STEP 4.1) stemmed e$corpus1
# e$tdm1:					(STEP 4.1) term-document matrix of e$corpus1stem / then complete the stemmed terms by method "prevalent"
# e$tdmm1:				(STEP 4.1) matrix format of e$tdm1
# e$freq1:				(STEP 4.1) terms frequency (all terms without removing sparsity) by descending order in named vector format
# e$wf1:					(STEP 4.1) words frequency in data frame format based on e$tdmm1
# e$spars:				(STEP 4.2) decimal indicating sparsity to be removed from e$tdm1
# e$tdm2:					(STEP 4.2) term-document matrix removing sparse terms from tdm1
# e$tdmm2:				(STEP 4.2) matrix format of e$tdm2
# e$freq2:				(STEP 4.2) terms frequency (sparsity removed) by descending order in named vector format
# e$wf2:					(STEP 4.2) words frequency in data frame format based on e$tdmm2
# e$ncol_freq:		(STEP 5.1) specified number of (top frequent) words to be applied on frequency plot (e$p2)
# e$min.freqh:		(STEP 5.1) the minimum frequency in the word frequency plot (e$p2)
# e$min.freqc:		(STEP 5.2) the minimum frequency of words for wordcloud
# e$min.freqa:		(STEP 5.3) the minimum frequency of words for association plot
# e$corth:				(STEP 5.3) the threshold of correlation of words for association plot
# e$clustk:				(STEP 5.4) number of clusters for K-means plot

# List of graphics
# e$p1:						(STEP 3) 1st plot on word frequency (top 20) 
# e$p2:						(STEP 5.1) 2nd plot on word frequency of specified number of (top frequent) words